config/routes.rb
Dnspanel::Application.routes.draw do
  resources :zone_updaters

  resources :zones do
    resources:records
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/record.rb
class TargetValidator <  ActiveModel::EachValidator
  def validate_each(record,attribute,value)
    if !(record.recordType=~/IN.A/).nil? and !(value=~/[A-z]/).nil?
      record.errors[:name]<<'A Record must be IP address'
    elsif !(record.recordType=~/IN.MX/).nil? and (value=~/^[0-9]* /).nil?
      record.errors[:name]<<'MX Records must hava a priority. EX: 10 example.com'
    end
    
  end
end

class Record < ActiveRecord::Base
  belongs_to :zone
  attr_accessible :source, :target, :recordType, :zone
  validates :recordType, :inclusion => {:in => ['IN MX','IN A', 'IN CNAME'], :message=> "%{value} is not an allowable record type"}
  validates :target, :presence=>true, :target=>true
  validates :source, :presence=>true
  before_save :update_zone
  before_destroy :update_zone

  def update_zone 
    self.zone.update_serial
  end
  
end

app/models/zone.rb
class Zone < ActiveRecord::Base
  attr_accessible :defaultIp, :domain, :serial
  has_many :records, :dependent => :destroy
  has_one :zone_updater, :dependent => :destroy
  accepts_nested_attributes_for :records
  validates :domain, :uniqueness => true

  def update_serial
    day=Time.now.strftime("%Y%m%d").to_i*100
    serialdate=self.serial.to_s.to_i
    if day>serialdate
      self.serial=day
    else
      self.serial=self.serial+1
    end
    self.save
  end
end

app/models/zone_updater.rb
class ZoneUpdater < ActiveRecord::Base
  belongs_to :zone
  attr_accessible :algorithim, :key, :server

  #send updates to dns server
  def push
    res = Dnsruby::Resolver.new(self.server)
    res.dnssec=false
    tsig=Dnsruby::RR.create({:name=>zone.domain,:type="TSIG",key=>self.key})
    update=Dnsruby::Update.new(zone.domain)
    #addtotheupdate
    tsig.apply(update) 
    response=res.send_message(update)
  end

  #update this zone file from DNS server
  def pull
    zt=Dnsruby::ZoneTransfer.new
    zt.transfer_type=Dnsruby::Types.AXFR
    zt.server=self.server
    zone=zt.transfer(self.zone.domain)
    zone.tsig=self.zone.domain+".", self.key
    soa=zone[0]
    recl=zone[1]
    for record in zone
      src,type,target=record.to_s.match(/([A-z\.0-9]*)[0-9\t ]*(IN\t[A-z]*)\t([A-z0-9\. ]*)/).captures
      if type=='IN\tMX' or type=='IN\tA' or type=='IN\tCNAME'
	createRecord(record)
      elsif type=='IN\tSOA'
        updateSerial(record)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def create
    @zone=Zone.find(params[:zone_id])
    @record=@zone.records.create(params[:record])
    redirect_to zone_path(@zone)
  end

  def edit
    @record = Record.find(params[:id])
  end

  # PUT /records/1
  # PUT /records/1.json
  def update
    @record = Record.find(params[:id])
    @zone=@record.zone
    respond_to do |format|
      if @record.update_attributes(params[:record])
        format.html { redirect_to @zone, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

def destroy
    @record = Record.find(params[:id])
    @zone = Zone.find(params[:zone_id])
    @record.destroy

    respond_to do |format|
      format.html { redirect_to(@zone, :notice => 'Record was successfully deleted.') }
      format.xml  { head :ok }
    end
  end

end

app/controllers/zone_updaters_controller.rb
class ZoneUpdatersController < ApplicationController
  # GET /zone_updaters
  # GET /zone_updaters.json
  def index
    @zone_updaters = ZoneUpdater.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zone_updaters }
    end
  end

  # GET /zone_updaters/1
  # GET /zone_updaters/1.json
  def show
    @zone_updater = ZoneUpdater.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zone_updater }
    end
  end

  # GET /zone_updaters/new
  # GET /zone_updaters/new.json
  def new
    @zone_updater = ZoneUpdater.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zone_updater }
    end
  end

  # GET /zone_updaters/1/edit
  def edit
    @zone_updater = ZoneUpdater.find(params[:id])
  end

  # POST /zone_updaters
  # POST /zone_updaters.json
  def create
    @zone_updater = ZoneUpdater.new(params[:zone_updater])

    respond_to do |format|
      if @zone_updater.save
        format.html { redirect_to @zone_updater, notice: 'Zone updater was successfully created.' }
        format.json { render json: @zone_updater, status: :created, location: @zone_updater }
      else
        format.html { render action: "new" }
        format.json { render json: @zone_updater.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zone_updaters/1
  # PUT /zone_updaters/1.json
  def update
    @zone_updater = ZoneUpdater.find(params[:id])

    respond_to do |format|
      if @zone_updater.update_attributes(params[:zone_updater])
        format.html { redirect_to @zone_updater, notice: 'Zone updater was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zone_updater.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zone_updaters/1
  # DELETE /zone_updaters/1.json
  def destroy
    @zone_updater = ZoneUpdater.find(params[:id])
    @zone_updater.destroy

    respond_to do |format|
      format.html { redirect_to zone_updaters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zones }
    end
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
    @zone = Zone.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zone }
    end
  end

  # GET /zones/new
  # GET /zones/new.json
  def new
    @zone = Zone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zone }
    end
  end

  # GET /zones/1/edit
  def edit
    @zone = Zone.find(params[:id])
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(params[:zone])

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render json: @zone, status: :created, location: @zone }
      else
        format.html { render action: "new" }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zones/1
  # PUT /zones/1.json
  def update
    @zone = Zone.find(params[:id])

    respond_to do |format|
      if @zone.update_attributes(params[:zone])
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_serial
    @zone=Zone.find(params[:id])
    @zone.update_serial
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone = Zone.find(params[:id])
    @zone.destroy

    respond_to do |format|
      format.html { redirect_to zones_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/zone_updaters_helper.rb
module ZoneUpdatersHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/home/index.html.erb
<h1>DNS Panel</h1>
<%= link_to "Zones", zones_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dnspanel</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/records/_form.html.erb
<%= form_for([:zone, @record]) do |f| %>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :recordType %><br />
    <%= f.text_field :recordType %>
  </div>
  <div class="field">
    <%= f.label :target %><br />
    <%= f.text_area :target %>
  </div>
  <p><%= f.submit %></p>
<% end %>

app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Back', @record.zone %>

app/views/zone_updaters/_form.html.erb
<%= form_for(@zone_updater) do |f| %>
  <% if @zone_updater.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone_updater.errors.count, "error") %> prohibited this zone_updater from being saved:</h2>

      <ul>
      <% @zone_updater.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :zone %><br />
    <%= f.text_field :zone %>
  </div>
  <div class="field">
    <%= f.label :algorithim %><br />
    <%= f.text_field :algorithim %>
  </div>
  <div class="field">
    <%= f.label :key %><br />
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :server %><br />
    <%= f.text_field :server %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zone_updaters/edit.html.erb
<h1>Editing zone_updater</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone_updater %> |
<%= link_to 'Back', zone_updaters_path %>

app/views/zone_updaters/index.html.erb
<h1>Listing zone_updaters</h1>

<table>
  <tr>
    <th>Zone</th>
    <th>Algorithim</th>
    <th>Key</th>
    <th>Server</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zone_updaters.each do |zone_updater| %>
  <tr>
    <td><%= zone_updater.zone %></td>
    <td><%= zone_updater.algorithim %></td>
    <td><%= zone_updater.key %></td>
    <td><%= zone_updater.server %></td>
    <td><%= link_to 'Show', zone_updater %></td>
    <td><%= link_to 'Edit', edit_zone_updater_path(zone_updater) %></td>
    <td><%= link_to 'Destroy', zone_updater, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zone updater', new_zone_updater_path %>

app/views/zone_updaters/new.html.erb
<h1>New zone_updater</h1>

<%= render 'form' %>

<%= link_to 'Back', zone_updaters_path %>

app/views/zone_updaters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Zone:</b>
  <%= @zone_updater.zone %>
</p>

<p>
  <b>Algorithim:</b>
  <%= @zone_updater.algorithim %>
</p>

<p>
  <b>Key:</b>
  <%= @zone_updater.key %>
</p>

<p>
  <b>Server:</b>
  <%= @zone_updater.server %>
</p>


<%= link_to 'Edit', edit_zone_updater_path(@zone_updater) %> |
<%= link_to 'Back', zone_updaters_path %>

app/views/zones/_form.html.erb
<%= form_for(@zone) do |f| %>
  <% if @zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
      <% @zone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :defaultIp %><br />
    <%= f.text_field :defaultIp %>
  </div>
  <div class="field">
    <%= f.label :domain %><br />
    <%= f.text_field :domain %>
  </div>
  <div class="field">
    <%= f.label :serial %><br />
    <%= f.number_field :serial %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<h1>Listing zones</h1>

<table>
  <tr>
    <th>Defaultip</th>
    <th>Domain</th>
    <th>Serial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @zones.each do |zone| %>
  <tr>
    <td><%= zone.defaultIp %></td>
    <td><%= zone.domain %></td>
    <td><%= zone.serial %></td>
    <td><%= link_to 'Show', zone %></td>
    <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
    <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zone', new_zone_path %>

app/views/zones/new.html.erb
<h1>New zone</h1>

<%= render 'form' %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Defaultip:</b>
  <%= @zone.defaultIp %>
</p>

<p>
  <b>Domain:</b>
  <%= @zone.domain %>
</p>

<p>
  <b>Serial:</b>
  <%= @zone.serial %>
</p>
<p>
  <b>Records:</b>
  <% @zone.records.each do |record| %>
    <p>
      <%= record.source %> 
      <%= record.recordType %> 
      <%= record.target %> 
      <%= link_to 'Edit', edit_zone_record_path(@zone,record) %> |
      <%= link_to 'Destroy', zone_record_path(@zone,record), :confirm => 'Are you sure?', :method => :delete %>
    </p>
  <% end %>

</br>
<h2>Add Zone Records</h2>
<%= form_for([@zone, @zone.records.build]) do |f| %>
  <div class="field">
    <%= f.label :source %>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :recordType %>
    <%= f.text_field :recordType %>
  </div>
  <div class="field">
    <%= f.label :target %>
    <%= f.text_field :target %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</br>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>